#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 25 12:17:03 2021

@author: komal
"""
import matplotlib.pyplot as plt 
import os
import numpy as np
from nibabel.testing import data_path
import cv2
import nibabel as nib
import cv2
import glob
from scipy.stats import norm, kurtosis
import os
import shutil
import sys
import math
import os
import sys
from PIL import Image
from os import path
direc="/home/komal/django-apps/testsite/QC_folder/*"
folder = sorted(glob.glob(direc))
for z in range(len(folder)):
    if "HU" in folder[z]:
        sub = sorted(glob.glob(folder[z]+"/*"))
        for x in range(len(sub)):
            if "HU" in sub[x]:
                dirpath = (folder[z]+"/")
                path_new_jpeg = "/home/komal/django-apps/testsite/jpeg_all"
                os.mkdir(path_new_jpeg)
                shutil.copy(path.join(dirpath,sub[x]), path_new_jpeg)
            
            # if "jpeg" in sub[x]:
            #     allimg = sorted(glob.glob(sub[x]+"/*"))
            #     widths, heights = zip(*(i.size for i in allimg))
            #     total_width = sum(widths)
            #     max_height = max(heights)
                
            #     new_im = Image.new('RGB', (total_width, max_height))
            #     for elem in allimg:
            #          im=Image.open(elem)
            #          new_im.paste(im, (1,0))
            #          new_im.save('new_' + elem + '.jpg')
